services:
  churn-risk-pipeline:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: churn-risk-pipeline
    volumes:
      - ..:/workspace
    command: python -m app.main --stage all

  churn-risk-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: churn-risk-web
    volumes:
      - ..:/workspace
    command: streamlit run app/web_app.py --server.address 0.0.0.0 --server.port 8501
    ports:
      - "8501:8501"
